export interface CatalogProduct {
  id: string;
  slug: string;
  name: string;
  description: string;
  price: number;
  discountPrice?: number | null;
  stock: number;
  imageUrl: string;
  category: { id: string; name: string };
  brand?: { id: string; name: string };
  rating: number;
  reviewCount: number;
  seller?: { id: string; name: string; email: string };
  reviews?: Array<{
    id: string;
    rating: number;
    comment: string;
    createdAt: Date;
    user: { name: string; avatar?: string | null };
  }>;
}

export const FALLBACK_PRODUCTS: CatalogProduct[] = [
  // Special Offer & Hero Products
  {
    id: "special-xbox-controller",
    slug: "special-xbox-controller",
    name: "Game Console Wireless Controller + PC Adapter",
    description: "High-performance wireless controller designed for competitive gaming on PC and Xbox console with textured grips, responsive haptic triggers, and low-latency wireless adapter included.",
    price: 195.0,
    discountPrice: 75.0,
    stock: 25,
    imageUrl: "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-gaming", name: "Gaming" },
    brand: { id: "brand-xbox", name: "Microsoft Xbox" },
    rating: 4.8,
    reviewCount: 38,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "smartwatch-s3",
    slug: "smartwatch-s3",
    name: "Gear S3 Classic LTE Smartwatch Dual",
    description: "Premium smartwatch with rotating stainless steel bezel, built-in speaker and microphone, advanced health monitoring, ECG sensor, and all-day battery life.",
    price: 685.0,
    discountPrice: 599.0,
    stock: 18,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-wearables", name: "Smart Watches" },
    brand: { id: "brand-samsung", name: "Samsung" },
    rating: 4.9,
    reviewCount: 42,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "smart-3d",
    slug: "smart-3d",
    name: "Ultra HD Smart 3D Television & Entertainment System",
    description: "Immersive 4K UHD smart TV with high dynamic range, AI audio processing, streaming entertainment apps, and ultra-thin bezel design.",
    price: 1100.0,
    discountPrice: 950.0,
    stock: 12,
    imageUrl: "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-tvs", name: "Televisions" },
    brand: { id: "brand-sony", name: "Sony" },
    rating: 4.7,
    reviewCount: 19,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },

  // Special Deals Tabbed Items (prod-1 to prod-8)
  {
    id: "prod-1",
    slug: "prod-1",
    name: "Wireless Audio Speakers with Bluetooth 5.0",
    description: "Rich room-filling sound with deep acoustic bass, durable fabric mesh, water-resistant housing, and seamless Bluetooth 5.0 pairing.",
    price: 750.0,
    discountPrice: 685.0,
    stock: 16,
    imageUrl: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-audio", name: "Speakers" },
    brand: { id: "brand-audio", name: "Harman Sound" },
    rating: 4.8,
    reviewCount: 27,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "prod-2",
    slug: "prod-2",
    name: "Tablet Air 3 WiFi 64GB Silver Touch",
    description: "Ultra-thin portable tablet featuring high-resolution Retina display, fast octa-core processing, front & rear HDR cameras, and full stylus support.",
    price: 1350.0,
    discountPrice: 1215.0,
    stock: 14,
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-tablets", name: "Laptops & Tablets" },
    brand: { id: "brand-apple", name: "Apple" },
    rating: 4.9,
    reviewCount: 51,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "prod-3",
    slug: "prod-3",
    name: "Portable Over-Ear Wireless Headphones",
    description: "Active noise-canceling headphones with plush memory foam earcups, crystal-clear vocal profile, and up to 35 hours of continuous playback.",
    price: 260.0,
    discountPrice: 215.0,
    stock: 22,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-audio", name: "Headphones" },
    brand: { id: "brand-sony", name: "Sony" },
    rating: 4.7,
    reviewCount: 34,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "prod-4",
    slug: "prod-4",
    name: "Gear S3 Classic LTE Smartwatch Dual",
    description: "Premium stainless steel smartwatch with customizable watch faces, fitness tracking, NFC contactless payments, and water-resistance.",
    price: 720.0,
    discountPrice: 685.0,
    stock: 15,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-wearables", name: "Smartphones & Wearables" },
    brand: { id: "brand-samsung", name: "Samsung" },
    rating: 4.8,
    reviewCount: 39,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "prod-5",
    slug: "prod-5",
    name: "Ultra HD 4K Action Camera Waterproof",
    description: "Rugged waterproof 4K action camera with electronic image stabilization, wide-angle lens, dual color screens, and bike/helmet mounts.",
    price: 580.0,
    discountPrice: 525.0,
    stock: 11,
    imageUrl: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-cameras", name: "Cameras" },
    brand: { id: "brand-gopro", name: "GoPro" },
    rating: 4.6,
    reviewCount: 18,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "prod-6",
    slug: "prod-6",
    name: "Multifunction Color Laser All-In-One Printer",
    description: "Fast wireless all-in-one printer with duplex printing, auto document feeder, sharp vibrant color printouts, and cloud printing integration.",
    price: 540.0,
    discountPrice: 480.0,
    stock: 9,
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-printers", name: "Printers" },
    brand: { id: "brand-hp", name: "HP" },
    rating: 4.5,
    reviewCount: 14,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "prod-7",
    slug: "prod-7",
    name: "Gaming Controller Station White Edition",
    description: "Next-generation haptic feedback wireless controller with custom tactile paddle buttons and textured ergonomic grip for marathon sessions.",
    price: 650.0,
    discountPrice: 599.0,
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-gaming", name: "Gaming" },
    brand: { id: "brand-sony", name: "PlayStation" },
    rating: 4.9,
    reviewCount: 46,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "prod-8",
    slug: "prod-8",
    name: "Smart Home Security Camera Wireless 1080p",
    description: "Crystal clear 1080p indoor/outdoor smart security camera with infrared night vision, two-way audio intercom, and instant mobile alerts.",
    price: 740.0,
    discountPrice: 685.0,
    stock: 17,
    imageUrl: "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-security", name: "Security" },
    brand: { id: "brand-ring", name: "Ring" },
    rating: 4.7,
    reviewCount: 23,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },

  // Bottom Widgets (bw-1 to bw-9)
  {
    id: "bw-1",
    slug: "bw-1",
    name: "Purple Wireless Headphones Pro",
    description: "Stylish purple noise-canceling headphones with 40mm neodymium drivers and ultra-soft protein leather ear cushions.",
    price: 130.0,
    discountPrice: 110.0,
    stock: 19,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-audio", name: "Headphones" },
    brand: { id: "brand-beats", name: "Beats" },
    rating: 5.0,
    reviewCount: 16,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bw-2",
    slug: "bw-2",
    name: "PowerBank Portable 20,000mAh",
    description: "Compact high-capacity 20,000mAh power bank with 22.5W fast charging, LED percentage indicator, and multi-port simultaneous output.",
    price: 59.0,
    discountPrice: 49.0,
    stock: 35,
    imageUrl: "https://images.unsplash.com/photo-1609592424109-dd9892f1b177?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-accessories", name: "Accessories" },
    brand: { id: "brand-anker", name: "Anker" },
    rating: 4.8,
    reviewCount: 31,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bw-3",
    slug: "bw-3",
    name: "White Wireless Gaming Headset",
    description: "Studio-grade wireless gaming headset featuring spatial audio, detachable noise-isolating broadcast microphone, and 30-hour battery life.",
    price: 180.0,
    discountPrice: 159.0,
    stock: 15,
    imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-gaming", name: "Gaming" },
    brand: { id: "brand-steelseries", name: "SteelSeries" },
    rating: 5.0,
    reviewCount: 22,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bw-4",
    slug: "bw-4",
    name: "Cellular Smart Watch Series 7",
    description: "All-screen Retina OLED smartwatch with blood oxygen monitor, GPS, emergency SOS, and independent cellular connectivity.",
    price: 210.0,
    discountPrice: 180.0,
    stock: 14,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-wearables", name: "Smart Watches" },
    brand: { id: "brand-apple", name: "Apple" },
    rating: 5.0,
    reviewCount: 40,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bw-5",
    slug: "bw-5",
    name: "Tactical Action Camcorder HD",
    description: "High-frame-rate action camera with extreme temperature tolerance, slow-motion recording, and waterproof case included.",
    price: 360.0,
    discountPrice: 320.0,
    stock: 10,
    imageUrl: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-cameras", name: "Cameras" },
    brand: { id: "brand-dji", name: "DJI" },
    rating: 4.6,
    reviewCount: 15,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bw-6",
    slug: "bw-6",
    name: "Smartphone Edge Curved 256GB",
    description: "Sleek flagship smartphone with dynamic AMOLED curved display, 50MP triple camera system, and ultra-fast warp charging.",
    price: 899.0,
    discountPrice: 799.0,
    stock: 12,
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-phones", name: "Smartphones" },
    brand: { id: "brand-samsung", name: "Samsung" },
    rating: 5.0,
    reviewCount: 48,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bw-7",
    slug: "bw-7",
    name: "Gear S3 Classic LTE Smartwatch Dual",
    description: "Classic styling meets digital innovation with rotating bezel and complete fitness tracking.",
    price: 720.0,
    discountPrice: 685.0,
    stock: 14,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-wearables", name: "Smart Watches" },
    brand: { id: "brand-samsung", name: "Samsung" },
    rating: 5.0,
    reviewCount: 29,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bw-8",
    slug: "bw-8",
    name: "Ultra HD 4K Digital Camera System",
    description: "Professional mirrorless camera system with fast autofocus, full frame sensor, and interchangeable lens mount.",
    price: 1390.0,
    discountPrice: 1250.0,
    stock: 6,
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-cameras", name: "Cameras" },
    brand: { id: "brand-canon", name: "Canon" },
    rating: 5.0,
    reviewCount: 33,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bw-9",
    slug: "bw-9",
    name: "Pro Laser Color Multifunction Printer",
    description: "Enterprise workgroup color laser printer with rapid printing speeds and robust network security.",
    price: 520.0,
    discountPrice: 480.0,
    stock: 8,
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-printers", name: "Printers" },
    brand: { id: "brand-brother", name: "Brother" },
    rating: 4.7,
    reviewCount: 17,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },

  // Best Sellers (bs-1 to bs-6)
  {
    id: "bs-1",
    slug: "bs-1",
    name: "Apple iPad Air 11-Inch M2 Chip 256GB WiFi",
    description: "Stunning Liquid Retina display with M2 power and landscape front camera.",
    price: 88000,
    discountPrice: 82500,
    stock: 12,
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-tablets", name: "Tablets" },
    brand: { id: "brand-apple", name: "Apple" },
    rating: 4.8,
    reviewCount: 24,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bs-2",
    slug: "bs-2",
    name: 'Apple MacBook Air 15" M3 Chip 16GB / 512GB',
    description: "Liquid Retina display with 18-hour battery life and ultralight fanless architecture.",
    price: 182000,
    discountPrice: 174900,
    stock: 8,
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-laptops", name: "Laptops" },
    brand: { id: "brand-apple", name: "Apple" },
    rating: 4.9,
    reviewCount: 35,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bs-3",
    slug: "bs-3",
    name: "Logitech MX Master 3S Wireless Performance Mouse",
    description: "Quiet clicks and 8K DPI track-on-glass optical sensor with MagSpeed electromagnetic scrolling.",
    price: 13900,
    discountPrice: 12500,
    stock: 14,
    imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-accessories", name: "Accessories" },
    brand: { id: "brand-logitech", name: "Logitech" },
    rating: 4.9,
    reviewCount: 62,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bs-4",
    slug: "bs-4",
    name: "Sony WH-1000XM5 Noise Canceling Headphones",
    description: "Industry-leading noise canceling with dual processors and exceptional hands-free calling.",
    price: 38500,
    discountPrice: 34900,
    stock: 15,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-audio", name: "Audio" },
    brand: { id: "brand-sony", name: "Sony" },
    rating: 4.9,
    reviewCount: 44,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bs-5",
    slug: "bs-5",
    name: "Samsung Galaxy Watch 6 Classic 47mm LTE",
    description: "Rotating stainless steel bezel with advanced wellness tracking, ECG, and sleep coaching.",
    price: 34990,
    discountPrice: 31900,
    stock: 10,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-wearables", name: "Smart Watches" },
    brand: { id: "brand-samsung", name: "Samsung" },
    rating: 4.7,
    reviewCount: 28,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "bs-6",
    slug: "bs-6",
    name: "Apple iPhone 16 Pro Max 256GB",
    description: "Natural Titanium finish with A18 Pro chip, 48MP Fusion camera, and extended battery endurance.",
    price: 165000,
    discountPrice: 159990,
    stock: 6,
    imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-smartphones", name: "Smartphones" },
    brand: { id: "brand-apple", name: "Apple" },
    rating: 4.9,
    reviewCount: 78,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },

  // Products Page Fallbacks (p-1 to p-6)
  {
    id: "p-1",
    slug: "p-1",
    name: "Apple iPhone 16 Pro Max 256GB",
    description: "Natural Titanium finish with A18 Pro chip and telephoto camera.",
    price: 165000,
    discountPrice: 159990,
    stock: 12,
    imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-smartphones", name: "Smartphones" },
    brand: { id: "brand-apple", name: "Apple" },
    rating: 4.9,
    reviewCount: 52,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "p-2",
    slug: "p-2",
    name: 'Apple MacBook Air 15" M3 Chip 16GB / 512GB',
    description: "Liquid Retina display with 18-hour battery life and fanless design.",
    price: 182000,
    discountPrice: 174900,
    stock: 8,
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-laptops", name: "Laptops" },
    brand: { id: "brand-apple", name: "Apple" },
    rating: 4.9,
    reviewCount: 39,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "p-3",
    slug: "p-3",
    name: "Sony WH-1000XM5 Noise Canceling Headphones",
    description: "Industry-leading noise canceling with dual processors and 30hr battery.",
    price: 38500,
    discountPrice: 34900,
    stock: 15,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-audio", name: "Audio" },
    brand: { id: "brand-sony", name: "Sony" },
    rating: 4.8,
    reviewCount: 47,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "p-4",
    slug: "p-4",
    name: "Samsung Galaxy Watch 6 Classic 47mm LTE",
    description: "Rotating bezel with advanced sleep tracking and ECG sensor.",
    price: 34990,
    discountPrice: 31900,
    stock: 5,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-wearables", name: "Smart Watches" },
    brand: { id: "brand-samsung", name: "Samsung" },
    rating: 4.7,
    reviewCount: 26,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "p-5",
    slug: "p-5",
    name: "Keychron K2 Pro Wireless Mechanical Keyboard",
    description: "Custom mechanical keyboard with QMK/VIA support, hot-swappable switches, and Bluetooth connectivity.",
    price: 12500,
    discountPrice: 11200,
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-accessories", name: "Keyboards" },
    brand: { id: "brand-keychron", name: "Keychron" },
    rating: 4.9,
    reviewCount: 31,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
  {
    id: "p-6",
    slug: "p-6",
    name: "Logitech MX Master 3S Wireless Performance Mouse",
    description: "Ergonomic wireless mouse with 8000 DPI sensor and electromagnetic MagSpeed wheel.",
    price: 13900,
    discountPrice: 12500,
    stock: 14,
    imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
    category: { id: "cat-accessories", name: "Mice" },
    brand: { id: "brand-logitech", name: "Logitech" },
    rating: 4.9,
    reviewCount: 55,
    seller: { id: "seller-official", name: "Amar Gadget Official Store", email: "support@amargadget.com" },
  },
];

export function findFallbackProduct(identifier: string): CatalogProduct | null {
  if (!identifier) return null;
  const normalized = identifier.toLowerCase().trim();

  // Exact ID or slug match
  const found = FALLBACK_PRODUCTS.find(
    (p) =>
      p.id.toLowerCase() === normalized ||
      p.slug.toLowerCase() === normalized
  );
  if (found) return found;

  // Partial match or slug-like comparison
  const partial = FALLBACK_PRODUCTS.find(
    (p) =>
      p.id.toLowerCase().includes(normalized) ||
      normalized.includes(p.id.toLowerCase()) ||
      p.slug.toLowerCase().includes(normalized) ||
      normalized.includes(p.slug.toLowerCase())
  );
  if (partial) return partial;

  // Fallback to first product if query starts with known prefix
  if (normalized.startsWith("prod-") || normalized.startsWith("bw-") || normalized.startsWith("bs-") || normalized.startsWith("p-")) {
    return FALLBACK_PRODUCTS[0];
  }

  return null;
}
